#!/usr/bin/env python3
"""Single source of truth for publications + projects.

Reads assets/data/catalog.json and writes
  * assets/js/catalog.js               (window.CATALOG, for the quick-look popups)
  * index.html         between  <!-- catalog:pub-strip -->  / <!-- catalog:proj-strip -->
  * publications.html  between  <!-- catalog:pub-list -->
  * projects.html      between  <!-- catalog:proj-list -->
Static HTML is generated (not rendered client-side) so the pages stay indexable.
Re-run after editing catalog.json:  python3 scripts/build_catalog.py
"""
import json, re, pathlib, html

ROOT = pathlib.Path(__file__).resolve().parent.parent
cat = json.loads((ROOT / "assets/data/catalog.json").read_text())

ARROW_L = '<button class="c-btn prev" aria-label="Previous slide"><svg viewBox="0 0 24 24"><polyline points="15 6 9 12 15 18"/></svg></button>'
ARROW_R = '<button class="c-btn next" aria-label="Next slide"><svg viewBox="0 0 24 24"><polyline points="9 6 15 12 9 18"/></svg></button>'

def attr(s): return html.escape(s, quote=True)

def link_html(l):
    ext = "" if l.get("internal") else ' target="_blank" rel="noopener"'
    return f'<a href="{attr(l["href"])}"{ext}>{l["label"]}</a>'

def links_html(item):
    return '<div class="links">' + "".join(link_html(l) for l in item["links"]) + "</div>"

def thumb_html(item):
    imgs, alts = item["images"], item.get("alts", [])
    fit = f' class="fit-{item.get("fit", "cover")}"'
    if len(imgs) > 1:
        slides = "".join(f'<div class="slide"><img src="{attr(src)}" alt="{attr(alts[i] if i < len(alts) else "")}" decoding="async"{fit}></div>' for i, src in enumerate(imgs))
        return f'<div class="pub-thumb"><div class="pub-carousel" data-carousel><div class="carousel-track">{slides}</div>{ARROW_L}{ARROW_R}</div></div>'
    out = f'<img src="{attr(imgs[0])}" alt="{attr(alts[0] if alts else "")}" loading="lazy" decoding="async"{fit}>'
    if item.get("video"):
        out += f'<div class="hover-video"><video muted autoplay loop playsinline preload="none"><source src="{attr(item["video"])}" type="video/mp4"></video></div>'
    return f'<div class="pub-thumb">{out}</div>'

def pub_row(p):
    venue = f'<em>{p["venue"]}</em>, {p["year"]}' + (f' &middot; {p["note"]}' if p.get("note") else "")
    return f'''    <div class="pub card card-hover" id="{p["id"]}">
      {thumb_html(p)}
      <div class="pub-meta">
        <a href="{attr(p["href"])}" target="_blank" rel="noopener"><span class="papertitle">{p["title"]}</span></a>
        <span class="authors">{p["authors"]}</span>
        <span class="venue">{venue}</span>
        {links_html(p)}
        <p class="pub-desc">{p["desc"]}</p>
      </div>
    </div>'''

def proj_row(p):
    return f'''    <div class="pub card card-hover" id="{p["id"]}">
      {thumb_html(p)}
      <div class="pub-meta">
        <span class="papertitle">{p["title"]}</span><span class="proj-year">{p["year"]}</span>
        <p class="proj-body">{p["desc"]}</p>
        {links_html(p)}
      </div>
    </div>'''

def strip_card(kind, p):
    page = "publications.html" if kind == "publications" else "projects.html"
    tag = f'{p["venue"]} {p["year"]}' if kind == "publications" else f'{p.get("tag", "Project")} {p["year"]}'
    sub = p["authors"] if kind == "publications" else p["desc"]
    fit = f' class="fit-{p.get("fit", "cover")}"'
    alt = (p.get("alts") or [""])[0]
    return f'''      <a class="slide" href="{page}#{p["id"]}" data-kind="{kind}" data-id="{p["id"]}">
        <span class="slide-media"><img src="{attr(p["images"][0])}" alt="{attr(alt)}" loading="lazy" decoding="async"{fit}></span>
        <span class="slide-tag">{tag}</span>
        <span class="slide-body">
          <span class="slide-title">{p.get("short", p["title"])}</span>
          <span class="slide-sub">{sub}</span>
          <span class="slide-cta">Quick look</span>
        </span>
      </a>'''

def inject(path, marker, body):
    f = ROOT / path; s = f.read_text()
    pat = re.compile(rf"(<!-- catalog:{marker} -->)(.*?)(<!-- /catalog:{marker} -->)", re.S)
    assert pat.search(s), f"marker {marker} missing in {path}"
    s = pat.sub(lambda m: m.group(1) + "\n" + body + "\n" + m.group(3), s)
    f.write_text(s); print(f"  {path}: {marker} ({len(body)} chars)")

pubs, projs = cat["publications"], cat["projects"]
(ROOT / "assets/js/catalog.js").write_text("/* generated by scripts/build_catalog.py from assets/data/catalog.json */\nwindow.CATALOG = " + json.dumps(cat, ensure_ascii=False) + ";\n")
print("  assets/js/catalog.js")
inject("publications.html", "pub-list", "\n\n".join(pub_row(p) for p in pubs))
inject("projects.html", "proj-list", "\n\n".join(proj_row(p) for p in projs))
inject("index.html", "pub-strip", "\n".join(strip_card("publications", p) for p in pubs))
inject("index.html", "proj-strip", "\n".join(strip_card("projects", p) for p in projs))
print("done:", len(pubs), "publications,", len(projs), "projects")
